package br.com.mpro3.MproEntity;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/**
 * In one {@see br.com.mpro3.MproEntity.Entity} noted class is required one integer field with @Id annotation
 * for map the identifier primary key auto generated by SQLite
 */

@Retention(RetentionPolicy.RUNTIME)
public @interface Id
{
}
